services:
  - type: web
    name: face-detection
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn face_detection_project.wsgi
