services:
  - type: web
    name: face-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn FACE_DETECTION.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
